Make JSON change detection robust to diff errors
git diff can fail sometimes; in that case we assume that non-json files
changed.

diff --git a/build-scripts/files_changed b/build-scripts/files_changed
--- a/build-scripts/files_changed
+++ b/build-scripts/files_changed
@@ -7,8 +7,10 @@
 
 if [ -n $TRAVIS_COMMIT_RANGE ]
 then
-    # If this string is populated, it will work.
-    git diff --name-only $TRAVIS_COMMIT_RANGE
+    # If this string is populated, it should work.
+    # But it mught fail, due to e.g. the shallow clone depth missing the
+    # relevant commit, in which case we fail
+    git diff --name-only $TRAVIS_COMMIT_RANGE || exit 1
 else
     # The only time it isn't populated is on a new PR branch, where THIS will work.
     git diff --name-only $TRAVIS_BRANCH
